### ISSUE TITLE
Use of KEYS is discouraged

### ISSUE THREAD

**Issue by dominics** [simonedeponti/play26-lettuce#4]
The `removeAll` method is implemented in terms of the `KEYS` command. This is discouraged because it'll block all use of the server for all other clients while it runs, causing latency for all the other named caches implemented for the same instance. Thus the advice from Redis upstream is:

> Don't use KEYS in your regular application code

It'd be better to either:

- Instead of implementing named caches as key-prefixed caches, require them to use separate connection settings e.g. database number. This still provides any number of databases per server instance (configurable with the `databases` config parameter), and also provides `FLUSHDB` allowing keys to be cleared without an expensive `KEYS prefix*` command to retrieve them first.

Or

- Implement `removeAll` in terms of a `SCAN` iteration

**Comment by simonedeponti** [comment]
Tough question :smiley: 

I'd prefer, technically speaking, going with option 1, but that would mean some configuration changes (i.e. having a map between database number and cache name). The mapping is IMHO necessary so that is explicit and we don't have problems with ordering changing accidentally causing a cache reading from another one.

The latter option is less invasive but also looks quite expensive. I'll have a try tomorrow with option 1 and see how much would it change

**Comment by dominics** [comment]
Opened a PR with what option 2 would look like, but definitely feel free to close it if you think it's better to go the other way.

**Comment by simonedeponti** [comment]
I reviewed option 1 and the config is already there: if you create another cache other than default then it needs to have its own `lettuce.$cachename.url` config parameter, and one can use different database numbers for different caches.

The difference is that previously two different caches could go on the same redis database, now it's not possible anymore: I'll add a warning in the doc and when the module comes up do a configuration check and refuse to proceed if two caches are bound to the same URL.

**Comment by simonedeponti** [comment]
Okay, I did a bit of mistakes with issue numbers... but commit db0d2220573785802bf687e12e9b2bad436422ae should solve the issue

**Comment by dominics** [comment]
Awesome @simonedeponti - thanks for the help!
